#!/usr/bin/python

import os, re
try:
    sql = open("/home/ubuntu/workspace/judobnb/sql.dump").read()
except:
    sql = open("./sql.dump")
    print sql.read()
    exit()
oldd = "judobnb.creativegeek.jp"
newd = "www.judobnb.com"
splitted = sql.split(oldd)
result = []
for i in range(len(splitted)):
        
        thestr = splitted[i]#[-100:]#+"192.168.1.2:23369"+splitted[i+1][:100]
        
        if ';s:' in thestr[-15:]:
            #print thestr[-100:]
            splthestr = thestr.split(";")
            # s:107:blabla
            sr = splthestr[-1]
            var = sr.split(":")
            

            try:
                length = int(var[1])
                newlength = length + abs(len(newd) - len(oldd))
                var[1] = str(newlength)
      
                splthestr[-1]  = ":".join(var)
                
                newthestr = ";".join(splthestr)
                
                result.append(newthestr)
            except Exception,e:
                print "ERROR_STR:",e
                exit(2)
                
        else:
            result.append(thestr)
     
print newd.join(result)

# print "judobnb.creativegeek.jp".join(result)
# print (splitted[-2][-100:])+"192.168.1.2.:23662"+splitted[-1][:100]

# out = "".join([f+"judobnb.creativegeek.jp" for f in splitted[:-1]])+splitted[-1]
# #print out  